---
version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: lab123
    networks:
      - backend
  web:
    build: .
    ports:
      - "8080:5000"
    networks:
      - backend
      - public
networks:
  backend:
    driver: bridge
  public:
    driver: bridge