---
version: '2.0'
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - backend
  web:
    build: .
    ports:
      - "8080:5000"
    networks:
      - backend
      - public
networks:
  backend:
    driver: bridge
  public:
    driver: bridge